# Generated by Django 6.1 on 2026-08-31 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Телефонен номер')),
                ('car_model', models.CharField(blank=True, help_text='напр. Mercedes-Benz CLK 320', max_length=100, verbose_name='Автомобил (Марка и модел)')),
                ('bio', models.TextField(blank=True, help_text='Кратко описание за теб като шофьор или пътник', max_length=500, verbose_name='За мен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
