# Generated by Django 6.1 on 2026-08-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_pics/default.png', upload_to='profile_pics/', verbose_name='Профилна снимка'),
        ),
    ]
