# Generated by Django 6.1 on 2026-09-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook профил'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram профил'),
        ),
    ]
