# Generated by Django 6.1 on 2026-09-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_facebook_url_profile_instagram_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='profile_pics/', verbose_name='Профилна снимка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(help_text='Кратко описание за теб като шофьор или пътник', max_length=500, verbose_name='За мен'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='car_model',
            field=models.CharField(help_text='напр. Mercedes-Benz S 63', max_length=100, verbose_name='Автомобил (Марка и модел)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Телефонен номер'),
        ),
    ]
