# Generated by Django 6.1 on 2026-08-18 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('ride', 'passenger')},
        ),
        migrations.RemoveField(
            model_name='ride',
            name='allows_pets',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='allows_smoking',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='has_big_trunk',
        ),
        migrations.AlterField(
            model_name='booking',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seats_booked',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ride',
            name='available_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driven_rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
