# Generated by Django 6.1 on 2026-09-02 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('rides', '0004_ridemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rides.ride'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking', 'Нова резервация'), ('cancellation', 'Отказ от резервация'), ('chat', 'Ново съобщение'), ('review', 'Нов отзив')], max_length=20),
        ),
    ]
